/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design.view;


import java.sql.ResultSet;

import static connection.DB.eQuery;
import static helper.HelperData.fillTable;

/**
 *
 * @author novar
 */
public class MasterDashboard extends javax.swing.JPanel {

    /**
     * Creates new form MasterDashboard
     */
    public MasterDashboard() {
        initComponents();
        refreshTable();
        refreshData();
    }

    private void refreshTable() {
        try {
            String sql = "SELECT o.ID, o.DATE, o.ORDERER, o.STATUS, FORMAT(SUM(IFNULL(od.subtotal,0)), 'c', 'id-ID') AS `PRICING`, m.ID AS `ID MEMBER`, m.name AS `NAMA MEMBER` " +
                        "FROM orders o LEFT JOIN members m ON o.member_id = m.id LEFT JOIN order_details od ON o.id = od.order_id " +
                        "WHERE o.date BETWEEN DATE_SUB(NOW(), INTERVAL 30 DAY) AND NOW() GROUP BY o.id ORDER BY o.id DESC";
            fillTable(tblData, eQuery(sql));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void refreshData() {
        try {
            String sql = "SELECT COUNT(o.id) AS ORDERS, FORMAT(SUM(IFNULL(subtotal,0)), 'c', 'id-ID') AS REVENUE " +
                        "FROM orders o LEFT JOIN order_details od on o.id = od.order_id " +
                        "WHERE o.date BETWEEN DATE_SUB(NOW(), INTERVAL 30 DAY) AND NOW() GROUP BY o.id";

            ResultSet result = eQuery(sql);
            result.next();
            lbOrders.setText(result.getString("ORDERS"));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new Palette.Custom_JTabel();
        cardAnggota = new Palette.Custom_JPanelRounded();
        lb_orders = new javax.swing.JLabel();
        lbOrders = new javax.swing.JLabel();
        cardAnggota3 = new Palette.Custom_JPanelRounded();
        lb_anggota3 = new javax.swing.JLabel();
        lbJumlahPengembalian = new javax.swing.JLabel();
        cardAnggota2 = new Palette.Custom_JPanelRounded();
        lb_anggota2 = new javax.swing.JLabel();
        lbJumlahPeminjaman = new javax.swing.JLabel();
        cardAnggota1 = new Palette.Custom_JPanelRounded();
        lb_anggota1 = new javax.swing.JLabel();
        lbRevenue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tblData.setBackground(new java.awt.Color(255, 255, 255));
        tblData.setForeground(new java.awt.Color(255, 255, 255));
        tblData.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(tblData);

        cardAnggota.setBackground(new java.awt.Color(255, 255, 255));
        cardAnggota.setRoundBottomLeft(30);
        cardAnggota.setRoundBottomRight(30);
        cardAnggota.setRoundTopLeft(30);
        cardAnggota.setRoundTopRight(30);

        lb_orders.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lb_orders.setForeground(new java.awt.Color(51, 153, 0));
        lb_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_purchase_order_30px.png"))); // NOI18N
        lb_orders.setText("ORDERS");

        lbOrders.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbOrders.setForeground(new java.awt.Color(0, 0, 0));
        lbOrders.setText("0");

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOrders)
                    .addComponent(lb_orders))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_orders)
                .addGap(20, 20, 20)
                .addComponent(lbOrders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardAnggota3.setBackground(new java.awt.Color(255, 255, 255));
        cardAnggota3.setPreferredSize(new java.awt.Dimension(217, 123));
        cardAnggota3.setRoundBottomLeft(30);
        cardAnggota3.setRoundBottomRight(30);
        cardAnggota3.setRoundTopLeft(30);
        cardAnggota3.setRoundTopRight(30);

        lb_anggota3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lb_anggota3.setForeground(new java.awt.Color(255, 153, 0));
        lb_anggota3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_cost_30px.png"))); // NOI18N
        lb_anggota3.setText("COST");

        lbJumlahPengembalian.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbJumlahPengembalian.setForeground(new java.awt.Color(0, 0, 0));
        lbJumlahPengembalian.setText("Coming Soon");

        javax.swing.GroupLayout cardAnggota3Layout = new javax.swing.GroupLayout(cardAnggota3);
        cardAnggota3.setLayout(cardAnggota3Layout);
        cardAnggota3Layout.setHorizontalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJumlahPengembalian)
                    .addComponent(lb_anggota3))
                .addGap(140, 140, 140))
        );
        cardAnggota3Layout.setVerticalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_anggota3)
                .addGap(20, 20, 20)
                .addComponent(lbJumlahPengembalian)
                .addGap(20, 20, 20))
        );

        cardAnggota2.setBackground(new java.awt.Color(255, 255, 255));
        cardAnggota2.setPreferredSize(new java.awt.Dimension(217, 123));
        cardAnggota2.setRoundBottomLeft(30);
        cardAnggota2.setRoundBottomRight(30);
        cardAnggota2.setRoundTopLeft(30);
        cardAnggota2.setRoundTopRight(30);

        lb_anggota2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lb_anggota2.setForeground(new java.awt.Color(0, 204, 204));
        lb_anggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_bullish_filled_30px.png"))); // NOI18N
        lb_anggota2.setText("PROFIT");

        lbJumlahPeminjaman.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbJumlahPeminjaman.setForeground(new java.awt.Color(0, 0, 0));
        lbJumlahPeminjaman.setText("Coming Soon");

        javax.swing.GroupLayout cardAnggota2Layout = new javax.swing.GroupLayout(cardAnggota2);
        cardAnggota2.setLayout(cardAnggota2Layout);
        cardAnggota2Layout.setHorizontalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJumlahPeminjaman)
                    .addComponent(lb_anggota2))
                .addGap(140, 140, 140))
        );
        cardAnggota2Layout.setVerticalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_anggota2)
                .addGap(20, 20, 20)
                .addComponent(lbJumlahPeminjaman)
                .addGap(20, 20, 20))
        );

        cardAnggota1.setBackground(new java.awt.Color(255, 255, 255));
        cardAnggota1.setRoundBottomLeft(30);
        cardAnggota1.setRoundBottomRight(30);
        cardAnggota1.setRoundTopLeft(30);
        cardAnggota1.setRoundTopRight(30);

        lb_anggota1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lb_anggota1.setForeground(new java.awt.Color(204, 0, 204));
        lb_anggota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_sales_performance_filled_30px.png"))); // NOI18N
        lb_anggota1.setText("REVENUE");

        lbRevenue.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbRevenue.setForeground(new java.awt.Color(0, 0, 0));
        lbRevenue.setText("0");

        javax.swing.GroupLayout cardAnggota1Layout = new javax.swing.GroupLayout(cardAnggota1);
        cardAnggota1.setLayout(cardAnggota1Layout);
        cardAnggota1Layout.setHorizontalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRevenue)
                    .addComponent(lb_anggota1))
                .addGap(140, 140, 140))
        );
        cardAnggota1Layout.setVerticalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_anggota1)
                .addGap(20, 20, 20)
                .addComponent(lbRevenue)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Master Data > Dashboard");

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Order Last 30 days");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(601, 601, 601)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cardAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel1))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardAnggota3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(cardAnggota2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(cardAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardAnggota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_JPanelRounded cardAnggota;
    private Palette.Custom_JPanelRounded cardAnggota1;
    private Palette.Custom_JPanelRounded cardAnggota2;
    private Palette.Custom_JPanelRounded cardAnggota3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJumlahPeminjaman;
    private javax.swing.JLabel lbJumlahPengembalian;
    private javax.swing.JLabel lbOrders;
    private javax.swing.JLabel lbRevenue;
    private javax.swing.JLabel lb_anggota1;
    private javax.swing.JLabel lb_anggota2;
    private javax.swing.JLabel lb_anggota3;
    private javax.swing.JLabel lb_orders;
    private Palette.Custom_JTabel tblData;
    // End of variables declaration//GEN-END:variables
}
