/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design.view;

/**
 *
 * @author novar
 */
public class MasterAddOrders extends javax.swing.JPanel {

    /**
     * Creates new form MasterOrders
     */
    public MasterAddOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        custom_JTabel2 = new Palette.Custom_JTabel();
        jPanel1 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        custom_JTextFieldRounded1 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded2 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded3 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded4 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded5 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded6 = new Palette.Custom_JTextFieldRounded();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        custom_JTextFieldRounded7 = new Palette.Custom_JTextFieldRounded();
        jLabel12 = new javax.swing.JLabel();
        custom_JTextFieldRounded8 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded9 = new Palette.Custom_JTextFieldRounded();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        custom_JTextFieldRounded10 = new Palette.Custom_JTextFieldRounded();
        jLabel15 = new javax.swing.JLabel();
        custom_JTextFieldRounded11 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded12 = new Palette.Custom_JTextFieldRounded();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        custom_ButtonRounded2 = new Palette.Custom_ButtonRounded();
        custom_ButtonRounded1 = new Palette.Custom_ButtonRounded();
        jPanel2 = new javax.swing.JPanel();
        pn_payment = new javax.swing.JPanel();

        custom_JTabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(custom_JTabel2);

        setPreferredSize(new java.awt.Dimension(1116, 673));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Details Orders");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_edit_property_30px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Add New Order");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_add_30px_2.png"))); // NOI18N

        custom_JTextFieldRounded1.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded1.setOpaque(true);
        custom_JTextFieldRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded1ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded2.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded2.setOpaque(true);
        custom_JTextFieldRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded2ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded3.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded3.setOpaque(true);

        custom_JTextFieldRounded4.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded4.setOpaque(true);

        custom_JTextFieldRounded5.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded5.setOpaque(true);
        custom_JTextFieldRounded5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded5ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded6.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded6.setOpaque(true);
        custom_JTextFieldRounded6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded6ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Admin");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Member ID");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Order Name");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("jLabel5");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("jLabel5");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ID");

        custom_JTextFieldRounded7.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded7.setOpaque(true);
        custom_JTextFieldRounded7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded7ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Order ID");

        custom_JTextFieldRounded8.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded8.setOpaque(true);
        custom_JTextFieldRounded8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded8ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded9.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded9.setOpaque(true);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Service ID");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Quantity");

        custom_JTextFieldRounded10.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded10.setOpaque(true);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Total");

        custom_JTextFieldRounded11.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded11.setOpaque(true);
        custom_JTextFieldRounded11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded11ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded12.setBackground(new java.awt.Color(0, 102, 255));
        custom_JTextFieldRounded12.setOpaque(true);
        custom_JTextFieldRounded12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded12ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("=");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Price");

        custom_ButtonRounded2.setBackground(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded2.setText("Add");
        custom_ButtonRounded2.setFillOriginal(new java.awt.Color(255, 153, 0));
        custom_ButtonRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButtonRounded2ActionPerformed(evt);
            }
        });

        custom_ButtonRounded1.setBackground(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded1.setText("Go To Payment");
        custom_ButtonRounded1.setFillOriginal(new java.awt.Color(255, 153, 0));
        custom_ButtonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButtonRounded1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        pn_payment.setBackground(new java.awt.Color(255, 255, 255));
        pn_payment.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_payment, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_utamaLayout = new javax.swing.GroupLayout(pn_utama);
        pn_utama.setLayout(pn_utamaLayout);
        pn_utamaLayout.setHorizontalGroup(
            pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_utamaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pn_utamaLayout.createSequentialGroup()
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_utamaLayout.createSequentialGroup()
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(custom_JTextFieldRounded8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(custom_JTextFieldRounded7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(60, 60, 60)
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(custom_JTextFieldRounded10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addGroup(pn_utamaLayout.createSequentialGroup()
                                            .addComponent(custom_JTextFieldRounded9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel16))
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel15)
                                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(custom_JTextFieldRounded12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(custom_JTextFieldRounded11, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(custom_ButtonRounded1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_utamaLayout.createSequentialGroup()
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(custom_JTextFieldRounded2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(custom_JTextFieldRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(60, 60, 60)
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(custom_JTextFieldRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(custom_JTextFieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addGap(60, 60, 60)
                                    .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(custom_JTextFieldRounded5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(custom_JTextFieldRounded6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(custom_ButtonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        pn_utamaLayout.setVerticalGroup(
            pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_utamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_utamaLayout.createSequentialGroup()
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custom_JTextFieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custom_JTextFieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custom_JTextFieldRounded6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custom_JTextFieldRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custom_JTextFieldRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custom_JTextFieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custom_ButtonRounded2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custom_JTextFieldRounded7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custom_JTextFieldRounded9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custom_JTextFieldRounded8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custom_JTextFieldRounded10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custom_JTextFieldRounded11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custom_JTextFieldRounded12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addComponent(custom_ButtonRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel1.add(pn_utama, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custom_JTextFieldRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded1ActionPerformed

    private void custom_JTextFieldRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded2ActionPerformed

    private void custom_JTextFieldRounded6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded6ActionPerformed

    private void custom_JTextFieldRounded5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded5ActionPerformed

    private void custom_JTextFieldRounded7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded7ActionPerformed

    private void custom_JTextFieldRounded8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded8ActionPerformed

    private void custom_JTextFieldRounded11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded11ActionPerformed

    private void custom_JTextFieldRounded12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded12ActionPerformed

    private void custom_ButtonRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButtonRounded2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_ButtonRounded2ActionPerformed

    private void custom_ButtonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButtonRounded1ActionPerformed
        pn_payment.removeAll();
        pn_payment.add(new Payment());
        pn_payment.repaint();
        pn_payment.revalidate();
    }//GEN-LAST:event_custom_ButtonRounded1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded custom_ButtonRounded1;
    private Palette.Custom_ButtonRounded custom_ButtonRounded2;
    private Palette.Custom_JTabel custom_JTabel2;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded1;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded10;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded11;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded12;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded2;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded3;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded4;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded5;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded6;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded7;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded8;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_payment;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
