/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design.view;

/**
 *
 * @author novar
 */
public class MasterMembership extends javax.swing.JPanel {

    /**
     * Creates new form MasterMembership
     */
    public MasterMembership() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custom_JTabel1 = new Palette.Custom_JTabel();
        jLabel3 = new javax.swing.JLabel();
        custom_ButtonRounded3 = new Palette.Custom_ButtonRounded();
        custom_JTextFieldRounded3 = new Palette.Custom_JTextFieldRounded();
        custom_ButtonRounded4 = new Palette.Custom_ButtonRounded();
        custom_JTextFieldRounded4 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded5 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded6 = new Palette.Custom_JTextFieldRounded();
        custom_JTextFieldRounded7 = new Palette.Custom_JTextFieldRounded();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));

        custom_JTabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(custom_JTabel1);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("List Of Membership");

        custom_ButtonRounded3.setBackground(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded3.setText("Delete");
        custom_ButtonRounded3.setFillOriginal(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        custom_ButtonRounded3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButtonRounded3ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded3.setBackground(new java.awt.Color(255, 153, 51));
        custom_JTextFieldRounded3.setForeground(new java.awt.Color(255, 255, 255));
        custom_JTextFieldRounded3.setToolTipText("");
        custom_JTextFieldRounded3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        custom_JTextFieldRounded3.setOpaque(true);
        custom_JTextFieldRounded3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded3ActionPerformed(evt);
            }
        });

        custom_ButtonRounded4.setBackground(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded4.setText("Add");
        custom_ButtonRounded4.setFillOriginal(new java.awt.Color(0, 102, 255));
        custom_ButtonRounded4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        custom_ButtonRounded4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButtonRounded4ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded4.setBackground(new java.awt.Color(51, 102, 255));
        custom_JTextFieldRounded4.setForeground(new java.awt.Color(255, 255, 255));
        custom_JTextFieldRounded4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        custom_JTextFieldRounded4.setText("Search");
        custom_JTextFieldRounded4.setToolTipText("");
        custom_JTextFieldRounded4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        custom_JTextFieldRounded4.setOpaque(true);
        custom_JTextFieldRounded4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded4ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded5.setBackground(new java.awt.Color(255, 153, 51));
        custom_JTextFieldRounded5.setForeground(new java.awt.Color(255, 255, 255));
        custom_JTextFieldRounded5.setToolTipText("");
        custom_JTextFieldRounded5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        custom_JTextFieldRounded5.setOpaque(true);
        custom_JTextFieldRounded5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded5ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded6.setBackground(new java.awt.Color(255, 153, 51));
        custom_JTextFieldRounded6.setForeground(new java.awt.Color(255, 255, 255));
        custom_JTextFieldRounded6.setToolTipText("");
        custom_JTextFieldRounded6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        custom_JTextFieldRounded6.setOpaque(true);
        custom_JTextFieldRounded6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded6ActionPerformed(evt);
            }
        });

        custom_JTextFieldRounded7.setBackground(new java.awt.Color(255, 153, 51));
        custom_JTextFieldRounded7.setForeground(new java.awt.Color(255, 255, 255));
        custom_JTextFieldRounded7.setToolTipText("");
        custom_JTextFieldRounded7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        custom_JTextFieldRounded7.setOpaque(true);
        custom_JTextFieldRounded7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JTextFieldRounded7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("nama");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Phone");

        javax.swing.GroupLayout pn_utamaLayout = new javax.swing.GroupLayout(pn_utama);
        pn_utama.setLayout(pn_utamaLayout);
        pn_utamaLayout.setHorizontalGroup(
            pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
            .addGroup(pn_utamaLayout.createSequentialGroup()
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_utamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(pn_utamaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custom_JTextFieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custom_JTextFieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custom_JTextFieldRounded7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custom_JTextFieldRounded6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_utamaLayout.createSequentialGroup()
                                .addComponent(custom_ButtonRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(custom_ButtonRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(custom_JTextFieldRounded4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_utamaLayout.setVerticalGroup(
            pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_utamaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custom_JTextFieldRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custom_JTextFieldRounded6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(custom_ButtonRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custom_ButtonRounded3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custom_JTextFieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custom_JTextFieldRounded7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(custom_JTextFieldRounded4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pn_utama, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custom_ButtonRounded3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButtonRounded3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_ButtonRounded3ActionPerformed

    private void custom_JTextFieldRounded3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded3ActionPerformed

    private void custom_ButtonRounded4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButtonRounded4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_ButtonRounded4ActionPerformed

    private void custom_JTextFieldRounded4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded4ActionPerformed

    private void custom_JTextFieldRounded5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded5ActionPerformed

    private void custom_JTextFieldRounded6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded6ActionPerformed

    private void custom_JTextFieldRounded7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JTextFieldRounded7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_JTextFieldRounded7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded custom_ButtonRounded3;
    private Palette.Custom_ButtonRounded custom_ButtonRounded4;
    private Palette.Custom_JTabel custom_JTabel1;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded3;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded4;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded5;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded6;
    private Palette.Custom_JTextFieldRounded custom_JTextFieldRounded7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
