/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design;

import design.view.MasterAddOrders;
import design.view.MasterDashboard;
import design.view.MasterMembership;
import design.view.MasterOrders;

import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author Armandho
 */
public class FrMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     */

    private static String id_user;
    private static String nama_user;

    public FrMenu() {
        initComponents();
    }

    public static void setIdUser(String id_user) {
        FrMenu.id_user = id_user;
    }

    public static void setNamaUser(String nama_user) {
        FrMenu.nama_user = nama_user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_dashboard = new javax.swing.JPanel();
        pn_linedashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btdashboard = new javax.swing.JLabel();
        pn_Orders = new javax.swing.JPanel();
        pn_lineorders = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btOrders = new javax.swing.JLabel();
        pn_OrdersInfo = new javax.swing.JPanel();
        pn_lineordersinfo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btOrdersInfo = new javax.swing.JLabel();
        pn_Membership = new javax.swing.JPanel();
        pn_lineMembership = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btMembership = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_atas = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(0, 102, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(250, 768));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icon_washing_home.png"))); // NOI18N
        jLabel1.setText("DryLaund's");

        pn_dashboard.setBackground(new java.awt.Color(0, 102, 255));

        pn_linedashboard.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout pn_linedashboardLayout = new javax.swing.GroupLayout(pn_linedashboard);
        pn_linedashboard.setLayout(pn_linedashboardLayout);
        pn_linedashboardLayout.setHorizontalGroup(
            pn_linedashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_linedashboardLayout.setVerticalGroup(
            pn_linedashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_compass_30px.png"))); // NOI18N

        btdashboard.setBackground(new java.awt.Color(102, 102, 102));
        btdashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btdashboard.setForeground(new java.awt.Color(255, 255, 255));
        btdashboard.setText("Dashboard");
        btdashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btdashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btdashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_linedashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(pn_linedashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Orders.setBackground(new java.awt.Color(0, 102, 255));

        pn_lineorders.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout pn_lineordersLayout = new javax.swing.GroupLayout(pn_lineorders);
        pn_lineorders.setLayout(pn_lineordersLayout);
        pn_lineordersLayout.setHorizontalGroup(
            pn_lineordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pn_lineordersLayout.setVerticalGroup(
            pn_lineordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_add_rule_30px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btOrders.setBackground(new java.awt.Color(102, 102, 102));
        btOrders.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btOrders.setForeground(new java.awt.Color(255, 255, 255));
        btOrders.setText("Add Orders");
        btOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btOrdersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btOrdersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_OrdersLayout = new javax.swing.GroupLayout(pn_Orders);
        pn_Orders.setLayout(pn_OrdersLayout);
        pn_OrdersLayout.setHorizontalGroup(
            pn_OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lineorders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_OrdersLayout.setVerticalGroup(
            pn_OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(pn_lineorders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_OrdersInfo.setBackground(new java.awt.Color(0, 102, 255));

        pn_lineordersinfo.setBackground(new java.awt.Color(0, 102, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_purchase_order_30px_2.png"))); // NOI18N

        btOrdersInfo.setBackground(new java.awt.Color(102, 102, 102));
        btOrdersInfo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btOrdersInfo.setForeground(new java.awt.Color(255, 255, 255));
        btOrdersInfo.setText("Orders Info");
        btOrdersInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btOrdersInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btOrdersInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btOrdersInfoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_lineordersinfoLayout = new javax.swing.GroupLayout(pn_lineordersinfo);
        pn_lineordersinfo.setLayout(pn_lineordersinfoLayout);
        pn_lineordersinfoLayout.setHorizontalGroup(
            pn_lineordersinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lineordersinfoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOrdersInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_lineordersinfoLayout.setVerticalGroup(
            pn_lineordersinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(btOrdersInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_OrdersInfoLayout = new javax.swing.GroupLayout(pn_OrdersInfo);
        pn_OrdersInfo.setLayout(pn_OrdersInfoLayout);
        pn_OrdersInfoLayout.setHorizontalGroup(
            pn_OrdersInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OrdersInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lineordersinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_OrdersInfoLayout.setVerticalGroup(
            pn_OrdersInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OrdersInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lineordersinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_Membership.setBackground(new java.awt.Color(0, 102, 255));

        pn_lineMembership.setBackground(new java.awt.Color(0, 102, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/assets/icons8_membership_card_filled_30px_1.png"))); // NOI18N

        btMembership.setBackground(new java.awt.Color(102, 102, 102));
        btMembership.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btMembership.setForeground(new java.awt.Color(255, 255, 255));
        btMembership.setText("Membership");
        btMembership.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMembershipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMembershipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMembershipMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_lineMembershipLayout = new javax.swing.GroupLayout(pn_lineMembership);
        pn_lineMembership.setLayout(pn_lineMembershipLayout);
        pn_lineMembershipLayout.setHorizontalGroup(
            pn_lineMembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lineMembershipLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineMembershipLayout.setVerticalGroup(
            pn_lineMembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(btMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_MembershipLayout = new javax.swing.GroupLayout(pn_Membership);
        pn_Membership.setLayout(pn_MembershipLayout);
        pn_MembershipLayout.setHorizontalGroup(
            pn_MembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MembershipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lineMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_MembershipLayout.setVerticalGroup(
            pn_MembershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MembershipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lineMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pn_Membership, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_OrdersInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Orders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(pn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_OrdersInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Membership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_atas.setBackground(new java.awt.Color(204, 204, 204));
        pn_atas.setPreferredSize(new java.awt.Dimension(1116, 95));

        javax.swing.GroupLayout pn_atasLayout = new javax.swing.GroupLayout(pn_atas);
        pn_atas.setLayout(pn_atasLayout);
        pn_atasLayout.setHorizontalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
        );
        pn_atasLayout.setVerticalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_atas, java.awt.BorderLayout.PAGE_START);

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.add(pn_utama, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btdashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashboardMouseEntered
        pn_dashboard.setBackground(new Color(255, 165, 0)); // Warna orange
        pn_linedashboard.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_btdashboardMouseEntered

    private void btdashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashboardMouseExited
        pn_dashboard.setBackground(new Color(0, 102, 255)); // Warna biru
        pn_linedashboard.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btdashboardMouseExited

    private void btdashboardMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btdashboardMouseClicked
        pn_utama.setVisible(true);
        pn_utama.removeAll();
        pn_utama.add(new MasterDashboard());
        pn_utama.setBackground(Color.white);
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_btdashboardMouseClicked

    private void btOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersMouseExited
        pn_Orders.setBackground(new Color(0, 102, 255));
        pn_lineorders.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btOrdersMouseExited

    private void btOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersMouseEntered
        pn_Orders.setBackground(new Color(255, 165, 0)); // Warna orange
        pn_lineorders.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_btOrdersMouseEntered

    private void btOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersMouseClicked
        pn_utama.setVisible(true);
        pn_utama.removeAll();
        pn_utama.add(new MasterAddOrders());
        pn_utama.setBackground(Color.white);
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btOrdersMouseClicked

    private void btOrdersInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersInfoMouseEntered
        pn_OrdersInfo.setBackground(new Color(255, 165, 0)); // Warna orange
        pn_lineordersinfo.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_btOrdersInfoMouseEntered

    private void btOrdersInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersInfoMouseExited
        pn_OrdersInfo.setBackground(new Color(0, 102, 255));
        pn_lineordersinfo.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btOrdersInfoMouseExited

    private void btOrdersInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrdersInfoMouseClicked
        pn_utama.setVisible(true);
        pn_utama.removeAll();
        pn_utama.add(new MasterOrders());
        pn_utama.setBackground(Color.white);
        pn_utama.repaint();
        pn_utama.revalidate();
        
        
    }//GEN-LAST:event_btOrdersInfoMouseClicked

    private void btMembershipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMembershipMouseEntered
        pn_Membership.setBackground(new Color(255, 165, 0)); // Warna orange
        pn_lineMembership.setBackground(new Color(255, 165, 0));
    }//GEN-LAST:event_btMembershipMouseEntered

    private void btMembershipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMembershipMouseExited
        pn_Membership.setBackground(new Color(0, 102, 255));
        pn_lineMembership.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btMembershipMouseExited
    private void btMembershipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMembershipMouseClicked
        pn_utama.setVisible(true);
        pn_utama.removeAll();
        pn_utama.add(new MasterMembership());
        pn_utama.setBackground(Color.white);
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btMembershipMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        pn_utama.setVisible(true);
        pn_utama.removeAll();
        pn_utama.add(new MasterAddOrders());
        pn_utama.setBackground(Color.white);
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btMembership;
    private javax.swing.JLabel btOrders;
    private javax.swing.JLabel btOrdersInfo;
    private javax.swing.JLabel btdashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pn_Membership;
    private javax.swing.JPanel pn_Orders;
    private javax.swing.JPanel pn_OrdersInfo;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_dashboard;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_lineMembership;
    private javax.swing.JPanel pn_linedashboard;
    private javax.swing.JPanel pn_lineorders;
    private javax.swing.JPanel pn_lineordersinfo;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
